import { Box, Container, Icon } from '@mui/material';
import Head from 'next/head';

import styles from './PageTemplate.module.scss';

const PageTemplate = (props: {children?: React.ReactNode}) => {
  return (
    <Container maxWidth="xl">
      <Head>
        <title>Yet another TODO app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
      </Head>

      <main className={styles.main}>
        <header className={styles.header}>
          <Icon sx={{ fontSize: 50, paddingRight: 4 }}>receipt_long</Icon> Yet another TODO app
        </header>

        <Box className={styles.box} >
          {props.children}
        </Box>

        <footer className={styles.footer}>
          {(new Date).getFullYear()} &copy; Anupama
        </footer>
      </main>
    </Container>
  )
}

export default PageTemplate
