import type { NextPage } from 'next'
import Head from 'next/head'

import styles from '../styles/Home.module.scss'

import AddCard from '../Components/AddCard'
import GridCard from '../Components/GridCard'

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faListCheck } from '@fortawesome/free-solid-svg-icons'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Yet another TODO app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className={styles.title}>
        <FontAwesomeIcon icon={faListCheck} /> Yet another TODO app
      </h1>
      <main className={styles.main}>
        <section className={styles.grid}>
          <AddCard />
          <GridCard id="1" title="First" />
          <GridCard id="2" title="Second" />
          <GridCard id="3" title="Third" />
          <GridCard id="4" title="Fourth" />
        </section>
      </main>

      <footer className={styles.footer}>
        {(new Date).getFullYear()} &copy; Anupama
      </footer>
    </div>
  )
}

export default Home
