import { useState } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'

import { Dialog } from '@reach/dialog'
import '@reach/dialog/styles.css'

import styles from '../styles/Home.module.scss'

import AddCard from '../Components/AddCard'
import GridCard from '../Components/GridCard'

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faListCheck } from '@fortawesome/free-solid-svg-icons'
import { useAppDispatch, useAppSelector } from '../State/Hooks'
import { createTodoListAction } from '../State/Slice'

const Home: NextPage = () => {

  const dispatch = useAppDispatch()

  const todoMap = useAppSelector(state => state.data)

  const [showDialog, setShowDialog] = useState(false)
  const openDialog = () => setShowDialog(true)
  const closeDialog = () => setShowDialog(false)

  const [listName, setListName] = useState('')

  const addList = () => {
    dispatch(createTodoListAction(listName));
    setListName('');
    closeDialog();
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Yet another TODO app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className={styles.title}>
        <FontAwesomeIcon icon={faListCheck} /> Yet another TODO app
      </h1>
      <main className={styles.main}>
        <section className={styles.grid}>
          <AddCard onClick={openDialog} />
          {Object.values(todoMap).map(it => (
            <GridCard key={it.id} todoList={it} />
          ))}
        </section>
        <Dialog isOpen={showDialog} aria-label="Add Dialog">
          <input value={listName} onChange={e => setListName(e.target.value)} />
          <button onClick={closeDialog}>Cancel</button>
          <button onClick={addList}>Add</button>
        </Dialog>
      </main>

      <footer className={styles.footer}>
        {(new Date).getFullYear()} &copy; Anupama
      </footer>
    </div>
  )
}

export default Home
